//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airquality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instruments()
        {
            this.Measurements = new HashSet<Measurements>();
        }
    
        public int OpstillingId { get; set; }
        public string Kode { get; set; }
        public Nullable<int> MaalestedId { get; set; }
        public Nullable<int> UdstyrId { get; set; }
    
        public virtual Equipments Equipments { get; set; }
        public virtual Stations Stations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measurements> Measurements { get; set; }
    }
}
