//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airquality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTM()
        {
            this.Stations = new HashSet<Stations>();
        }
    
        public int GeometriId { get; set; }
        public Nullable<int> UTMX { get; set; }
        public Nullable<int> UTMY { get; set; }
        public Nullable<int> UTMZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stations> Stations { get; set; }
    }
}
